CONFIG_MAIN_STACK_SIZE=2048

CONFIG_BT=y
CONFIG_BT_ISO_MAX_CHAN=2

CONFIG_LOG=y

# Allow debugging in Ozone
CONFIG_DEBUG=y

# Force the mac address to be static random
CONFIG_BT_PRIVACY=n

# to enable static random address which does not change
# CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
